version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      POSTGRES_DB: synthea
      POSTGRES_USER: api
      POSTGRES_PASSWORD: jw8s0F4
    ports:
      - "${DB_PORT}:${DB_PORT}"

  app:
    build: .
    depends_on:
      - db
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql://api:jw8s0F4@db:${DB_PORT}/synthea
    ports:
      - "${PORT}:${PORT}"

volumes:
  postgres_data: